### ISSUE TITLE
AsyncRead/Write not implemented for TcpStream

### ISSUE THREAD

**Issue by PvdBerg1998** [withoutboats/romio#71]
Hey.
I'll just give a code example:
```rust
// This is futures 0.3 alpha 13
use futures::prelude::*;

// AsyncWriteExt requires AsyncWrite, the same for -Read
fn do_something<S: AsyncReadExt + AsyncWriteExt>(stream: &mut S) {}

let mut tcp_stream: TcpStream = blabla;
do_something(&mut tcp_stream);
```

This works with tokio's `TcpStream`, but with `Romio`, this fails with the following error:
```
the trait futures::io::AsyncRead is not implemented for romio::tcp::stream::TcpStream
```

But: https://github.com/withoutboats/romio/blob/master/src/tcp/stream.rs#L518 ??

**Comment by PvdBerg1998** [comment]
Minimal example:
Cargo.toml
```toml
[dependencies]
futures-preview = { version = "^0.3.0-alpha.13", features = ["compat", "io-compat"], git = "https://github.com/rust-lang-nursery/futures-rs" }
romio = { version = "^0.3.0-alpha.2", git = "https://github.com/withoutboats/romio" }
```
main.rs:
```rust
use futures::prelude::*;
use romio::TcpStream;

fn main() {
    let mut tcp_stream: TcpStream = unimplemented!();
    do_something(&mut tcp_stream);
}

fn do_something<S: AsyncReadExt + AsyncWriteExt>(stream: &mut S) {}
```
